<?php

namespace App\Support;

class OrganizationThemes
{
    public const DEFAULT = 'embers';

    public static function presets(): array
    {
        return [
            'embers' => [
                'name' => 'Embers',
                'mode' => 'dark',
                'eyebrow' => 'text-amber-300',
                'header_heading' => 'text-stone-100',
                'header_button' => 'bg-amber-300 text-stone-950',
                'header_back' => 'border-white/10 bg-white/5 text-stone-200',
                'surface' => 'border-white/10 bg-stone-900/70 text-stone-100 ring-white/10',
                'hero' => 'bg-[radial-gradient(circle_at_top_left,_rgba(251,146,60,0.16),_transparent_30%),linear-gradient(135deg,_#292524,_#0c0a09)]',
                'hero_overlay' => 'from-stone-950 via-stone-950/20',
                'logo_shell' => 'border-white/10 bg-black/40 text-amber-200',
                'hero_eyebrow' => 'text-amber-200/80',
                'hero_heading' => 'text-white',
                'meta' => 'text-stone-400',
                'heading' => 'text-stone-100',
                'muted' => 'text-stone-500',
                'body' => 'text-stone-300',
                'link' => 'text-amber-300',
                'soft_button' => 'border-white/10 bg-white/5 text-stone-200',
                'accent_button' => 'bg-emerald-300 text-stone-950',
                'accent_badge' => 'border-emerald-300/30 bg-emerald-300/10 text-emerald-200',
                'report_button' => 'border-amber-300/30 bg-white/5 text-stone-200',
                'danger_button' => 'border-rose-300/30 bg-white/5 text-stone-200',
                'panel' => 'border-white/10 bg-black/20',
                'input' => 'border-white/10 bg-white/5 text-stone-100 placeholder:text-stone-500',
                'primary_button' => 'bg-amber-300 text-stone-950',
                'secondary_button' => 'bg-emerald-400 text-stone-950',
                'checkbox' => 'text-emerald-400 focus:ring-emerald-400',
                'facebook_checkbox' => 'text-blue-400 focus:ring-blue-400',
            ],
            'midnight' => [
                'name' => 'Midnight',
                'mode' => 'dark',
                'eyebrow' => 'text-sky-300',
                'header_heading' => 'text-slate-100',
                'header_button' => 'bg-sky-300 text-slate-950',
                'header_back' => 'border-white/10 bg-white/5 text-slate-200',
                'surface' => 'border-white/10 bg-slate-950/80 text-slate-100 ring-sky-400/15',
                'hero' => 'bg-[radial-gradient(circle_at_top_left,_rgba(56,189,248,0.2),_transparent_32%),linear-gradient(135deg,_#0f172a,_#020617)]',
                'hero_overlay' => 'from-slate-950 via-slate-950/25',
                'logo_shell' => 'border-sky-300/20 bg-slate-950/70 text-sky-200',
                'hero_eyebrow' => 'text-sky-200/80',
                'hero_heading' => 'text-white',
                'meta' => 'text-slate-400',
                'heading' => 'text-slate-100',
                'muted' => 'text-slate-500',
                'body' => 'text-slate-300',
                'link' => 'text-sky-300',
                'soft_button' => 'border-white/10 bg-white/5 text-slate-200',
                'accent_button' => 'bg-sky-300 text-slate-950',
                'accent_badge' => 'border-sky-300/30 bg-sky-300/10 text-sky-200',
                'report_button' => 'border-sky-300/30 bg-white/5 text-slate-200',
                'danger_button' => 'border-rose-300/30 bg-white/5 text-slate-200',
                'panel' => 'border-white/10 bg-slate-900/60',
                'input' => 'border-white/10 bg-white/5 text-slate-100 placeholder:text-slate-500',
                'primary_button' => 'bg-sky-300 text-slate-950',
                'secondary_button' => 'bg-cyan-300 text-slate-950',
                'checkbox' => 'text-sky-400 focus:ring-sky-400',
                'facebook_checkbox' => 'text-blue-400 focus:ring-blue-400',
            ],
            'forest' => [
                'name' => 'Forest',
                'mode' => 'dark',
                'eyebrow' => 'text-lime-300',
                'header_heading' => 'text-stone-100',
                'header_button' => 'bg-lime-300 text-stone-950',
                'header_back' => 'border-white/10 bg-white/5 text-stone-200',
                'surface' => 'border-lime-200/10 bg-[#111814]/85 text-stone-100 ring-lime-300/10',
                'hero' => 'bg-[radial-gradient(circle_at_top_left,_rgba(163,230,53,0.18),_transparent_34%),linear-gradient(135deg,_#1a2e1f,_#08110b)]',
                'hero_overlay' => 'from-[#08110b] via-[#08110b]/25',
                'logo_shell' => 'border-lime-200/15 bg-black/40 text-lime-200',
                'hero_eyebrow' => 'text-lime-200/80',
                'hero_heading' => 'text-lime-50',
                'meta' => 'text-stone-400',
                'heading' => 'text-lime-50',
                'muted' => 'text-stone-500',
                'body' => 'text-stone-300',
                'link' => 'text-lime-300',
                'soft_button' => 'border-white/10 bg-white/5 text-stone-200',
                'accent_button' => 'bg-lime-300 text-stone-950',
                'accent_badge' => 'border-lime-300/30 bg-lime-300/10 text-lime-200',
                'report_button' => 'border-lime-300/25 bg-white/5 text-stone-200',
                'danger_button' => 'border-rose-300/30 bg-white/5 text-stone-200',
                'panel' => 'border-white/10 bg-black/20',
                'input' => 'border-white/10 bg-white/5 text-stone-100 placeholder:text-stone-500',
                'primary_button' => 'bg-lime-300 text-stone-950',
                'secondary_button' => 'bg-emerald-300 text-stone-950',
                'checkbox' => 'text-lime-400 focus:ring-lime-400',
                'facebook_checkbox' => 'text-blue-400 focus:ring-blue-400',
            ],
            'paper' => [
                'name' => 'Paper',
                'mode' => 'light',
                'eyebrow' => 'text-amber-700',
                'header_heading' => 'text-stone-900',
                'header_button' => 'bg-stone-900 text-stone-50',
                'header_back' => 'border-stone-300 bg-white text-stone-700',
                'surface' => 'border-stone-200 bg-white text-stone-900 ring-stone-200',
                'hero' => 'bg-[radial-gradient(circle_at_top_left,_rgba(251,191,36,0.18),_transparent_30%),linear-gradient(135deg,_#fffaf0,_#f5f5f4)]',
                'hero_overlay' => 'from-white via-white/10',
                'logo_shell' => 'border-stone-200 bg-white/90 text-amber-700',
                'hero_eyebrow' => 'text-amber-700/80',
                'hero_heading' => 'text-stone-950',
                'meta' => 'text-stone-600',
                'heading' => 'text-stone-900',
                'muted' => 'text-stone-500',
                'body' => 'text-stone-700',
                'link' => 'text-amber-700',
                'soft_button' => 'border-stone-300 bg-white text-stone-700',
                'accent_button' => 'bg-amber-300 text-stone-950',
                'accent_badge' => 'border-emerald-300/40 bg-emerald-100 text-emerald-800',
                'report_button' => 'border-amber-300/50 bg-amber-50 text-stone-800',
                'danger_button' => 'border-rose-300/40 bg-rose-50 text-rose-800',
                'panel' => 'border-stone-200 bg-stone-50',
                'input' => 'border-stone-300 bg-white text-stone-900 placeholder:text-stone-400',
                'primary_button' => 'bg-stone-900 text-stone-50',
                'secondary_button' => 'bg-emerald-400 text-stone-950',
                'checkbox' => 'text-emerald-500 focus:ring-emerald-500',
                'facebook_checkbox' => 'text-blue-500 focus:ring-blue-500',
            ],
            'aurora' => [
                'name' => 'Aurora',
                'mode' => 'light',
                'eyebrow' => 'text-fuchsia-700',
                'header_heading' => 'text-slate-900',
                'header_button' => 'bg-fuchsia-600 text-white',
                'header_back' => 'border-slate-200 bg-white/70 text-slate-700',
                'surface' => 'border-fuchsia-200/50 bg-white/90 text-slate-900 ring-fuchsia-200/50',
                'hero' => 'bg-[radial-gradient(circle_at_top_left,_rgba(232,121,249,0.22),_transparent_28%),radial-gradient(circle_at_top_right,_rgba(34,211,238,0.18),_transparent_30%),linear-gradient(135deg,_#fdf4ff,_#ecfeff)]',
                'hero_overlay' => 'from-white/85 via-white/5',
                'logo_shell' => 'border-fuchsia-200 bg-white/80 text-fuchsia-700',
                'hero_eyebrow' => 'text-fuchsia-700/80',
                'hero_heading' => 'text-slate-950',
                'meta' => 'text-slate-600',
                'heading' => 'text-slate-900',
                'muted' => 'text-slate-500',
                'body' => 'text-slate-700',
                'link' => 'text-fuchsia-700',
                'soft_button' => 'border-slate-200 bg-white/75 text-slate-700',
                'accent_button' => 'bg-cyan-300 text-slate-950',
                'accent_badge' => 'border-cyan-300/50 bg-cyan-100 text-cyan-800',
                'report_button' => 'border-fuchsia-300/40 bg-fuchsia-50 text-slate-800',
                'danger_button' => 'border-rose-300/40 bg-rose-50 text-rose-800',
                'panel' => 'border-slate-200 bg-white/80',
                'input' => 'border-slate-200 bg-white text-slate-900 placeholder:text-slate-400',
                'primary_button' => 'bg-fuchsia-600 text-white',
                'secondary_button' => 'bg-cyan-300 text-slate-950',
                'checkbox' => 'text-fuchsia-500 focus:ring-fuchsia-500',
                'facebook_checkbox' => 'text-blue-500 focus:ring-blue-500',
            ],
            'harbor' => [
                'name' => 'Harbor',
                'mode' => 'light',
                'eyebrow' => 'text-sky-700',
                'header_heading' => 'text-slate-900',
                'header_button' => 'bg-sky-700 text-white',
                'header_back' => 'border-slate-200 bg-white/70 text-slate-700',
                'surface' => 'border-sky-200/50 bg-[#f4fbff] text-slate-900 ring-sky-200/50',
                'hero' => 'bg-[radial-gradient(circle_at_top_left,_rgba(56,189,248,0.18),_transparent_30%),linear-gradient(135deg,_#eefbff,_#eff6ff)]',
                'hero_overlay' => 'from-white/80 via-white/10',
                'logo_shell' => 'border-sky-200 bg-white/85 text-sky-700',
                'hero_eyebrow' => 'text-sky-700/80',
                'hero_heading' => 'text-slate-950',
                'meta' => 'text-slate-600',
                'heading' => 'text-slate-900',
                'muted' => 'text-slate-500',
                'body' => 'text-slate-700',
                'link' => 'text-sky-700',
                'soft_button' => 'border-slate-200 bg-white/80 text-slate-700',
                'accent_button' => 'bg-sky-700 text-white',
                'accent_badge' => 'border-sky-300/50 bg-sky-100 text-sky-800',
                'report_button' => 'border-sky-300/40 bg-sky-50 text-slate-800',
                'danger_button' => 'border-rose-300/40 bg-rose-50 text-rose-800',
                'panel' => 'border-slate-200 bg-white/80',
                'input' => 'border-slate-200 bg-white text-slate-900 placeholder:text-slate-400',
                'primary_button' => 'bg-sky-700 text-white',
                'secondary_button' => 'bg-emerald-400 text-slate-950',
                'checkbox' => 'text-sky-500 focus:ring-sky-500',
                'facebook_checkbox' => 'text-blue-500 focus:ring-blue-500',
            ],
        ];
    }

    public static function keys(): array
    {
        return array_keys(self::presets());
    }

    public static function get(?string $key): array
    {
        return self::presets()[$key ?? ''] ?? self::presets()[self::DEFAULT];
    }
}
